fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    registration:
        form:
            type: app_user_registration
    profile:
        form:
            type: app_user_profile
    from_email:
        address: noreply@freeyachting.com
        sender_name: FreeYachting.com
