# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@request"]
        scope: request
        tags:
         - { name: knp_menu.menu_builder, method: createSearchMenu, alias: search_menu }
         - { name: knp_menu.menu_builder, method: createBreadcrumbsMenu, alias: breadcrumbs }
    twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }
    app.form.registration:
        class: AppBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }
        arguments: [@?]
