sonata_media:
    db_driver: doctrine_orm
    default_context: default
    providers:
        image:
            resizer: sonata.media.resizer.square
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 100 }
        travel:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 260, height: 260, quality: 90 }
        yacht:
            providers:
                - sonata.media.provider.image
            formats:
                middle: { width: 550, quality: 100 }

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataMediaBundle: ~
                    ApplicationSonataMediaBundle: ~
